[Container]
Label=traefik.http.middlewares.%N-theme.plugin.themepark.app=adguardhome
Label=traefik.http.middlewares.%N-theme.plugin.themepark.theme=trueblack
Label=traefik.http.routers.%N.middlewares=%N-theme
